"""unique lead per inbox item

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 09:21:04.806631
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_leads_inbox_item_id'), 'leads', ['inbox_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_leads_inbox_item_id'), 'leads', type_='unique')
    # ### end Alembic commands ###
