"""vk id refresh tokens

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 11:28:03.716466
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_accounts', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('vk_accounts', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.add_column('vk_accounts', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vk_accounts', 'token_expires_at')
    op.drop_column('vk_accounts', 'device_id')
    op.drop_column('vk_accounts', 'refresh_token')
    # ### end Alembic commands ###
